accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_register'),
    path('verify_code/', views.UserRegisterVerifyView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('reset/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('delete_user/', views.DeleteUserView.as_view(), name='delete_user'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('post/', include('post.urls', namespace='post')),
    path('relation/', include('relation.urls', namespace='relation')),
]

post/models.py
from django.db import models
from accounts.models import User
# Create your models here.

class Post(models.Model):
    body = models.TextField(max_length=250)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.slug}'

    def Likes_count(self):
        return self.pvote.count()


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
    body = models.TextField(max_length=250)
    is_reply = models.BooleanField(default=False)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomment', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user}-{self.body[:30]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvote')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvote')

    def __str__(self):
        return f'{self.user} liked {self.post.slug}'

post/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

post/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from post.models import Post, Comment, Vote
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.utils.text import slugify


# Create your views here.
class PostDetailView(View):
    template_name = 'post/detail.html'
    form_class = CommentCreateForm
    form_reply_class = CommentReplyForm
    
    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, id=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, post_id, post_slug):
        post = get_object_or_404(Post, id = post_id, slug = post_slug)
        comments = post.pcomment.filter(is_reply=False)
        form = self.form_class
        return render(request, self.template_name, 
        {'post': post, 'comments': comments, 'form': form, 'reply_form': self.form_reply_class}
        )

    @method_decorator(login_required())
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'your comment submited successfully!', 'success')
            return redirect('post:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'post delete successfully!', 'success')
            return redirect('home:home')
        messages.error(request, 'you cant delete this post!', 'danger')
        return render(request, 'post/detail.html')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    template_name = 'post/update.html'


    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, id=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'you cant update this post!', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)


    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, self.template_name, {'form': form})
    

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'your post updated successfully!', 'success')
            return redirect('post:post_detail', post.id, post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    template_name = 'post/create.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form': form})
        

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit = False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'You share new post!', 'success')
            return redirect('post:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = Post.objects.get(id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply submitted successfully', 'success')
        return redirect('post:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Vote.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, 'you have already liked this post!')
        else:
            Vote.objects.create(post=post, user=request.user)
            messages.success(request, 'you liked this post!', 'success')
        return redirect('post:post_detail', post.id, post.slug)

post/templates/post/create.html
{% extends 'Base.html' %}
{% block content %}
<h2 class="text-center">CREATE POST</h2>

<form action="" method="post" class="col-md-6" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>
{%endblock%}

post/templates/post/detail.html
{% extends 'base.html' %}
{% block content %}

    {% if request.user.id == post.user.id %}
        <a href="{% url 'post:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'post:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}

    <p><a href="{% url 'accounts:user_profile' post.user.id %}">{{ post.user.username }}</a> - {{ post.updated|date:"Y-M" }}</p>
    <p>{{ post.body }}</p><hr/>

    {% if request.user.is_authenticated %}
        <a href="{% url 'post:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} btn btn-primary col-md-2">Like {{ post.Likes_count }}</a><br/>

        <form action="" method="post"><br/>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form> <br/>
    {% else %}
        <p class="alert alert-danger">Only logged in users can comment.</p>
    {% endif %}

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <p class="card-body">{{ comment.body }}</p>

            {% if request.user.is_authenticated %}
                <form action="{% url 'post:add_reply' post.id comment.id %}" method="post" >
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="send">
                </form>
            {% endif %}

            {% with replies=comment.rcomment.all %}
                {% for reply in replies %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }} <br/> {{ reply.body }}</p>
                {% endfor %}
            {% endwith %}
        </div><br/>
    {% empty %}
        <p>No comments yet!</p>
    {% endfor %}

{% endblock %}

post/templates/post/update.html
{% extends 'Base.html' %}
{% block content %}
<h2 class="text-center">UPDATE POST</h2>

<form action="" method="post" class="col-md-6" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{%endblock%}