accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='user_register'),
    path('verify_code/', views.UserRegisterVerifyView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('reset/', views.PasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('delete_user/', views.DeleteUserView.as_view(), name='delete_user'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),

]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('post/', include('post.urls', namespace='post')),
    path('relation/', include('relation.urls', namespace='relation')),
]

templates/inc/message.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{msg}}</p>
    {%endfor%}
{%endif%}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
        {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'accounts:user_logout' %}">Log Out</a>
            <a class="nav-link active" href="{% url 'accounts:user_profile'  request.user.id %}">Profile</a>
            {% if request.user.id == user.id %}
                <a href="{%url 'post:post_create' %}" class="nav-link active">Create New Post</a>
            {% endif %}
        {% else %}
            <a class="nav-link active" href="{% url 'accounts:user_register' %}">Register</a>
            <a class="nav-link active" href="{% url 'accounts:user_login' %}">Login</a>
        {% endif %}
        </div>
    </div>
</nav>